version: '3.3'

services:
  my_backend:
    platform: linux/x86_64
    image: asia.gcr.io/artiful-a1/my_backend:1.9
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.dev
    ports:
      - 3000:3000
    volumes:
      - ./src:/myfolder/src

  my_database:
    platform: linux/x86_64
    image: mysql:8.0.28
    environment:
      MYSQL_DATABASE: 'ars'
      MYSQL_ROOT_PASSWORD: '3160'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    cap_add:
      - SYS_NICE
    ports:
      - 3307:3306

  my_redis:
    image: redis:6.2.6
    ports:
      - 6379:6379

  elasticsearch:
    image: elasticsearch:7.17.0
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200

  logstash:
    image: logstash:7.17.0
    volumes:
      - ./elk/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./elk/logstash/mysql-connector-java-8.0.28.jar:/usr/share/logstash/mysql-connector-java-8.0.28.jar
